name: C/C++ CI

on:
  pull_request:
    branches:
      - wu_branch
  push:
    branches:
      - wu_branch

jobs:
  build:
    name: wutest
    runs-on: ubuntu-16.04
    container:
      image: docker://hsnuhayato/choreonoid1.7:latest
    steps:
      - uses: hsnuhayato/tsml@wu_branch
      - name: "make"
        run: |
          pwd;ls;
          cmake -H. -Bbuild;cd build;make install
