name: C/C++ CI

on:
  pull_request:
    branches:
      - wu_branch
  push:
    branches:
      - wu_branch

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - name: "make"
        uses: docker://hsnuhayato/choreonoid1.7:latest
        run: gitcheckout wu_branch;cmake -H. -Bbuild;cd build;make install
